### ISSUE TITLE
Use of `var` instead of `let` in solution.

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/js-basics-diagnostic#103]
Use of `var` in solution to diagnostic on README.

**Comment by jrhorn424** [comment]
Probably because the solution wasn't rebased after master was edited?

**Comment by laurenfazah** [comment]
Yeah, that old solution branch was a beginner's mistake on my part from 011. Created new `013/solution` branch and merged into new `solution` branch. Should be good to close now @berziiii @jrhorn424
