### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by raq929** [ga-wdi-boston/js-basics-diagnostic#166]
Make wording clearer.

**Comment by gaand** [comment]
@raq929 When you open an issue like this, you need to provide more information so someone else who looks at it will know what you're talking about without having to guess.

**Comment by raq929** [comment]
Some students had trouble figuring it out, and I thought maybe it could be clearer. But on second glance, it is quite clear. I wonder if in one of the initial diagnostics we should explicitly tell students to read the prompt at least twice before beginning to code. Sigh. Closing.

**Comment by jrhorn424** [comment]
@raq929 I've also considered having folks read instructions out loud.

**Comment by raq929** [comment]
I cannot stress how excellent I think that idea is.
