### ISSUE TITLE
Rebase and squash solution branch

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/js-basics-diagnostic#39]

**Comment by laurenfazah** [comment]
Created @jrhorn424

**Comment by jrhorn424** [comment]
Solution is out of sync with master. It should be rebased and force-pushed, optionally squashed to a single commit if it isn't already. Happy to close this afterward. I or @gaand can provide more detail.

**Comment by laurenfazah** [comment]
This goes along with my comment in #103. Should be fixed up now and issue is likely able to be closed @jrhorn424 @payne-chris-r

**Comment by jrhorn424** [comment]
@berziiii Please squash the commits on solution, and I'll close this. Thanks.

**Comment by raq929** [comment]
It looks like there is only one commit on solution. Can this issue be closed?

**Comment by raq929** [comment]
I have updated the solution branch and it is now one commit off master.

**Comment by jrhorn424** [comment]
Thanks!
